title: Settings
body: I'm thes fifth in the source order so I'm hidden when the page loads. I'm just shown if a link that references my id is beeing clicked.
body: bla bla lkjfojfoijofjaoifjaiosfjwoijkoioijoijii
body: oijdfojsaodfjasodfjosiafoasifjasodfiji
panel: I am the settings paneles .....!
